version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    reviewers:
      - "rodneyosodo"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    reviewers:
      - "rodneyosodo"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "./docker"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Africa/Nairobi"
    assignees:
      - "rodneyosodo"
    reviewers:
      - "rodneyosodo"
    commit-message:
      prefix: "chore"
      include: "scope"
